steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-search-story:$COMMIT_SHA', '.']

  # 2. Push the container image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-search-story:$COMMIT_SHA']

  # 3. Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        # The content of the secret is in the DOTENV_CONTENT env var.
        # Filter out comments, empty lines, and specific keys we want to override.
        BASE_VARS=$(echo "$$DOTENV_CONTENT" | grep -vE '^#|^$|^APP_PORT=|^GCP_PROJECT_ID=' | tr '\n' ',')

        # Construct the final string with our overrides.
        # Append the required Cloud Run port and the project ID from the build environment,
        # then append the variables from the secret.
        FINAL_VARS="APP_PORT=8080,GCP_PROJECT_ID=$PROJECT_ID,${BASE_VARS}"
        FINAL_VARS=$(echo $FINAL_VARS | sed 's/,$//')

        # Deploy using the constructed string
        gcloud run deploy my-search-story \
          --image=gcr.io/$PROJECT_ID/my-search-story:$COMMIT_SHA \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --set-env-vars="$FINAL_VARS"

# This section makes secrets from Secret Manager available to the build steps
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/My-Search-Story/versions/latest
      env: 'DOTENV_CONTENT'

images:
  - 'gcr.io/$PROJECT_ID/my-search-story:$COMMIT_SHA'